@hostname = 0.0.0.0
@port = 8042
@host = {{hostname}}:{{port}}

### get grid
GET  http://{{host}}/api/grid/

### create the grid
POST http://{{host}}/api/grid/
content-type: application/json

{"images":[
    {
        "id": 204900006,
        "message": "",
        "picture": "https://placeimg.com/2560/2560/any",
        "pictureSmall": "",
        "pictureMedium": "",
        "pictureStored": "",
        "timestamp": 1578391381
    },
    {
        "id": 204900003,
        "message": "",
        "picture": "https://placeimg.com/2560/2560/any",
        "pictureSmall": "",
        "pictureMedium": "",
        "pictureStored": "",
        "timestamp": 1578391381
    },{
        "id": 204900005,
        "message": "",
        "picture": "https://placeimg.com/2560/2560/any",
        "pictureSmall": "",
        "pictureMedium": "",
        "pictureStored": "",
        "timestamp": 1578391381
        }
]}
